name: authon
description: Official Authon SDK for Dart and Flutter
version: 0.1.0
homepage: https://github.com/mikusnuz/authon-sdk/tree/main/dart

environment:
  sdk: '>=3.0.0 <4.0.0'

dependencies:
  http: ^1.1.0
  crypto: ^3.0.0
